### ISSUE TITLE
BUG TransparentRandn

### ISSUE THREAD

**Issue by wuhao13** [HyperDbg/HyperDbg#51]
There appears to be a bug, get the value of this function often significantly more than expected in TransparentRandn, which can cause a lot of problems.

**Comment by wuhao13** [comment]
@SinaKarvandi I found that our HideDebugger function is not available, I hope you can improve this function.

**Comment by SinaKarvandi** [comment]
What do you mean by HideDebuger. Do you mean "TransparentHideDebugger"? what's wrong with it ?

**Comment by wuhao13** [comment]
@SinaKarvandi 
Yes, he has a problem in a physical computer. I think the writemsr method should not be used to modify MSR_IA32_TIME_STAMP_COUNTER.

**Comment by SinaKarvandi** [comment]
Yep, I experience some problems like graphic reset (Monitor) or music errors in Windows. But I thought I solved the problems as it didn't cause the error the last time that I checked it.

**Comment by wuhao13** [comment]
@SinaKarvandi Maybe you haven't tested it on a real computer. I did not have too many strange problems in the virtual machine test, but the black screen and other problems appeared on the real computer.

**Comment by wuhao13** [comment]
Maybe you haven't tested it on a physical computer. I did not have too many strange problems in the virtual machine test, but the black screen and other problems appeared on the real computer.

**Comment by wuhao13** [comment]
These problems are like rendering thread or graphics driver problems.

**Comment by SinaKarvandi** [comment]
Yep, I experienced the same issues on the physical computers. I have to re-test this functionality. Please keep us updated if you found a solution.

**Comment by wuhao13** [comment]
@SinaKarvandi I will continue to track this issue, but I think it will be convenient for us to solve this problem by solving the random number generator problem first.

**Comment by SinaKarvandi** [comment]
I think the problem is not because of the random number generator. For testing, you can return a constant number and you'll see how it behaves the same. Btw, @Sal3h should fix the random generator error. As it has some mathematics to simulate the behavior of float numbers with integer numbers that I'm not really involved.

**Comment by wuhao13** [comment]
@SinaKarvandi Sorry, please forgive my random guess, I will continue to study it.

I am busy writing a symbol resolution class recently. During this period, I found that your code does not seem to resolve kernel symbols?

**Comment by SinaKarvandi** [comment]
Well, kernel symbols are implemented in local debugging. Still, it has some design problems in remote debugging. But it works on local debugging.

**Comment by wuhao13** [comment]
Well, thanks for the code, it's really good!

**Comment by SinaKarvandi** [comment]
Thanks to you for always giving us your valuable feedbacks.

**Comment by Sal3h** [comment]
Hi, thanks for the feedback and excuse me for the delayed reply. I will check the function and get back to you ASAP.

**Comment by Sal3h** [comment]
I set the `Average` to 200 and a `Sigma` to 10 and the result was promising, what is the exact problem you're dealing with? @wuhao13 
![image_2021-08-30_14-00-14](https://user-images.githubusercontent.com/15903552/131319120-cdcf1b5d-032d-4a62-a7f5-b7dd039c3eeb.png)

**Comment by SinaKarvandi** [comment]
Please consider to re-open the issue if it's not yet solved.
Thanks

**Comment by lingdianvision** [comment]
> 貌似有一个bug，在TransparentRandn中获取这个函数的值往往明显超过预期，这会导致很多问题。



> 貌似有一个bug，在TransparentRandn中获取这个函数的值往往明显超过预期，这会导致很多问题。

看到你的ID 很想知道你是不是中国的，期待与你交流V1437974052

**Comment by lingdianvision** [comment]
@wuhao13 看到你的ID，很想问下你是不是中国的，期待与你交流。1437974052

**Comment by lingdianvision** [comment]
@wuhao13  看到你的ID，很感兴趣你不是中国的，期待与你交流。1437974052
